# Changes here will be overwritten by Copier
_commit: 0.0.10
_src_path: gh:reservoir-data/singer-tap-copier-template
author_email: edgarrm358@gmail.com
author_fullname: Edgar Ramírez-Mondragón
author_username: edgarrmondragon
python_main_version: '3.10'
repository_name: tap-belvo
repository_namespace: edgarrmondragon
repository_provider: github.com
tap_auth_method: Basic Auth
tap_id: tap-belvo
tap_package_command_line_name: tap-belvo
tap_package_distribution_name: tap-belvo
tap_package_import_name: tap_belvo
tap_source_description: The leading Open Banking API platform in Latin America
tap_source_id: Belvo
tap_source_name: Belvo
tap_stream_type: REST
vscode_files: true
